export type ProjectStatus = 'Shipped' | 'In Progress' | 'Open Source'

export interface ProjectLink {
  type: 'live' | 'appstore' | 'github'
  url: string
}

export interface Project {
  slug: string
  title: string
  tagline: string
  description: string
  role: string
  dates?: { start: string; end?: string } // 'YYYY-MM'; no end = present
  status: ProjectStatus
  stack: string[]
  highlights: string[]
  links: ProjectLink[]
  media?: { src: string; alt: string; kind: 'image' | 'video' }
}

// Add a project by appending to this array. Missing facts are marked TODO; never guess them.
export const projects: Project[] = [
  {
    slug: 'keystone',
    title: 'Keystone: Overcome Doubt',
    tagline: 'AI-powered self-reflection, built on Aristotle’s golden mean.',
    description:
      'An identity-alignment app: users define who they want to be, chat with an AI persona and log real-world actions, and an AI backend scores how well they are living up to it.',
    role: 'Solo founder',
    dates: { start: '2025-04' },
    status: 'Shipped',
    stack: ['React Native', 'Expo', 'TypeScript', 'Supabase', 'Superwall', 'EAS Build'],
    highlights: [
      'Six identity-key categories, each scored 0–1, with the ideal at the midpoint between deficiency and excess.',
      'Expo Router app on Supabase: auth, Postgres and Edge Functions.',
      'Freemium subscriptions through Superwall; shipped to the App Store with EAS Build.',
    ],
    links: [
      { type: 'live', url: 'https://www.thekeystoneapp.com/' },
      // TODO: add the Keystone App Store URL
    ],
    // TODO: add a screenshot or short video (public/projects/keystone.*)
  },
  {
    slug: 'a-virtue-a-day',
    title: 'A Virtue A Day',
    tagline: 'Virtue ethics, translated into a daily practice app.',
    description:
      'A mobile app for practicing ethical exercises in groups, built for a Calvin University ethics course with philosophy faculty: professors assign exercises, and students track daily progress, take notes and reflect.',
    role: 'Project manager and lead developer',
    dates: { start: '2025-06' },
    status: 'Shipped',
    stack: ['React Native', 'Expo', 'Supabase', 'PostgreSQL'],
    highlights: [
      'Group codes, plus owner-managed exercises with date ranges and daily-frequency targets.',
      'Daily progress tracking with auto-saved notes and swipe actions.',
      'Built with philosophy faculty to turn virtue-ethics frameworks into app features.',
    ],
    links: [
      // TODO: add the A Virtue A Day App Store URL
    ],
    // TODO: add a screenshot or short video
  },
  {
    slug: 'scale66',
    title: 'Scale66',
    tagline: 'On-brand social carousels, generated by an AI pipeline.',
    description:
      'A full-stack marketing automation SaaS that turns a brand kit and a prompt into complete carousel posts (captions, images and slide layouts) for Instagram, TikTok, LinkedIn and Twitter.',
    role: 'Co-founder and developer',
    dates: { start: '2025-08' },
    status: 'Open Source',
    stack: ['Next.js', 'TypeScript', 'FastAPI', 'Python', 'Supabase', 'Stripe', 'Claude', 'Gemini', 'GitHub Actions'],
    highlights: [
      'Next.js 15 frontend, FastAPI backend, Supabase for auth, Postgres and storage.',
      'Agentic AI pipeline: Claude for text and vision, Gemini for image generation.',
      'Led a small team with GitHub Issues; CI/CD through GitHub Actions.',
    ],
    links: [
      // TODO: add the public GitHub source URL
    ],
    // TODO: add a screenshot or short video
  },
]
